/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PanelRouteRouteImport } from './app/_panel/route'
import { Route as AuthRouteRouteImport } from './app/_auth/route'
import { Route as PanelIndexRouteImport } from './app/_panel/index'
import { Route as AuthLoginRouteImport } from './app/_auth/Login'
import { Route as PaneldashboardDashboardRouteImport } from './app/_panel/(dashboard)/Dashboard'

const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PaneldashboardDashboardRoute = PaneldashboardDashboardRouteImport.update({
  id: '/(dashboard)/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => PanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/Login': typeof AuthLoginRoute
  '/': typeof PanelIndexRoute
  '/Dashboard': typeof PaneldashboardDashboardRoute
}
export interface FileRoutesByTo {
  '/Login': typeof AuthLoginRoute
  '/': typeof PanelIndexRoute
  '/Dashboard': typeof PaneldashboardDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_panel': typeof PanelRouteRouteWithChildren
  '/_auth/Login': typeof AuthLoginRoute
  '/_panel/': typeof PanelIndexRoute
  '/_panel/(dashboard)/Dashboard': typeof PaneldashboardDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Login' | '/' | '/Dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/Login' | '/' | '/Dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/_panel'
    | '/_auth/Login'
    | '/_panel/'
    | '/_panel/(dashboard)/Dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_auth/Login': {
      id: '/_auth/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_panel/(dashboard)/Dashboard': {
      id: '/_panel/(dashboard)/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof PaneldashboardDashboardRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PanelRouteRouteChildren {
  PanelIndexRoute: typeof PanelIndexRoute
  PaneldashboardDashboardRoute: typeof PaneldashboardDashboardRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelIndexRoute: PanelIndexRoute,
  PaneldashboardDashboardRoute: PaneldashboardDashboardRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PanelRouteRoute: PanelRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
